/**
 * Country list for the quote form. Kept as a plain array rather than pulled
 * from a package so the bundle carries only the strings it needs.
 */
export const countries = [
  'United States',
  'Canada',
  'Mexico',
  'United Kingdom',
  'Ireland',
  'Germany',
  'France',
  'Netherlands',
  'Belgium',
  'Luxembourg',
  'Spain',
  'Portugal',
  'Italy',
  'Switzerland',
  'Austria',
  'Denmark',
  'Sweden',
  'Norway',
  'Finland',
  'Iceland',
  'Poland',
  'Czechia',
  'Slovakia',
  'Hungary',
  'Romania',
  'Bulgaria',
  'Greece',
  'Croatia',
  'Slovenia',
  'Serbia',
  'Estonia',
  'Latvia',
  'Lithuania',
  'Ukraine',
  'Turkey',
  'United Arab Emirates',
  'Saudi Arabia',
  'Qatar',
  'Kuwait',
  'Bahrain',
  'Oman',
  'Jordan',
  'Israel',
  'Egypt',
  'Morocco',
  'Algeria',
  'Tunisia',
  'Nigeria',
  'Ghana',
  'Kenya',
  'Tanzania',
  'Ethiopia',
  'South Africa',
  'Botswana',
  'Namibia',
  'Zambia',
  'India',
  'Pakistan',
  'Bangladesh',
  'Sri Lanka',
  'Nepal',
  'China',
  'Hong Kong SAR',
  'Taiwan',
  'Japan',
  'South Korea',
  'Singapore',
  'Malaysia',
  'Indonesia',
  'Thailand',
  'Vietnam',
  'Philippines',
  'Australia',
  'New Zealand',
  'Brazil',
  'Argentina',
  'Chile',
  'Colombia',
  'Peru',
  'Ecuador',
  'Uruguay',
  'Panama',
  'Costa Rica',
  'Dominican Republic',
  'Jamaica',
  'Trinidad and Tobago',
  'Other',
] as const;

export type Country = (typeof countries)[number];
